spring:
  application:
    name: covenantiq
  datasource:
    url: jdbc:h2:mem:covenantiqdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  mode:
    demo-enabled: false
    test-enabled: false
  seed:
    enabled: true
  security:
    enabled: true
  jwt:
    secret: "change-this-secret-for-prod-change-this-secret"
    access-token-minutes: 60
    refresh-token-days: 7
  workflow:
    bootstrap-default-alert-workflow-enabled: true
  webhook:
    encryption-key-base64: ${APP_WEBHOOK_ENCRYPTION_KEY_BASE64:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}

